<?php
    echo "Abs Examples";
    echo "<br>";
    echo abs(-2);
    echo "<br>";
    echo abs(3.58);
    echo "<br>";
    echo "<br>";
    echo "Ceil Examples";
    echo "<br>";
    echo ceil(3.8);
    echo "<br>";
    echo ceil(-3.9);
    echo "<br>";
    echo "<br>";
    echo "Floor Examples";
    echo "<br>";
    echo floor(3.2);
    echo "<br>";
    echo floor(-9.9);
    echo "<br>";
    echo "<br>";
    echo "Round up Examples";
    echo "<br>";
    echo round(2.3);
    echo "<br>";
    echo round(-5.9);
    echo "<br>";
    echo "<br>";
    echo "Squareroot Examples";
    echo "<br>";
    echo sqrt(-9);
    echo "<br>";
    echo sqrt(100);
    echo "<br>";
    echo "<br>";
    echo "Min Examples";
    echo "<br>";
    echo "(6,3.2,7,5,8,1,0)";
    echo "<br>";
    echo  min(6,3.2,7,5,8,1,0);
    echo "<br>";
    echo "<br>";
    echo "Max Examples";
    echo "<br>";
    echo "(6,3.2,7,5,8,1,0)";
    echo "<br>";
    echo  max(6,3.2,7,5,8,1,0);
    echo "<br>";
    echo "<br>";
    echo "Random Numbers Examples";
    echo "<br>";
    echo rand();
    echo "<br>";
    echo rand(6,25);
    echo "<br>";
    echo "<br>";
    echo "Power Examples";
    echo "<br>";
    echo pow(8,9);
    echo "<br>";
    echo pow(9,-7);
    echo "<br>";
    echo "<br>";
    echo "Fmod Examples";
    echo "<br>";
    $a=3;
    $b=9;
    echo fmod($b,$a);
    echo "<br>";
    echo "<br>";
?>